version: "3.9"

services:
  backend:
    image: mongo:latest
    container_name: py-cmdproxy-backend
    networks:
      - overlay
    ports:
      - "27017:27017"

  broker:
    image: redis:latest
    container_name: py-cmdproxy-broker
    networks:
      - overlay
    ports:
      - "6379:6379"

  cmdproxy:
    build: .
    image: cmdproxy.py:${CMDPROXY_VERSION}
    container_name: py-cmdproxy-server
    depends_on:
      - backend
      - broker
    networks:
      - overlay
    environment:
      - CMDPROXY_LOGLEVEL=DEBUG
      - CMDPROXY_REDIS_URL=redis://broker:6379
      - CMDPROXY_MONGO_URL=mongodb://backend:27017
      - CMDPROXY_MONGODB_NAME=cmdproxy-db

  client:
    build:
      context: .
      dockerfile: ./examples/Dockerfile.client
      args:
        - CMDPROXY_VERSION=${CMDPROXY_VERSION}
    image: cmdproxy.py/examples/client:${CMDPROXY_VERSION}
    container_name: py-cmdproxy-client
    depends_on:
      - backend
      - broker
    networks:
      - overlay
    environment:
      - CMDPROXY_REDIS_URL=redis://broker:6379
      - CMDPROXY_MONGO_URL=mongodb://backend:27017
      - CMDPROXY_MONGODB_NAME=cmdproxy-db
    profiles:
      - client

networks:
  overlay:
